---
- name: Scan multiple networks and add live IPs to NetBox
  hosts: localhost
  gather_facts: no

  vars:
    # Sæt dine egne værdier / brug vault eller env vars i praksis
    netbox_url: "https://10.20.1.143/api/"
    netbox_token: "c1fda850572c1fe314d59ac389b5c1fb75217141"

    # >>> Tilføj alle subnets her <<<
    scan_network_ranges:
      - "10.20.1.0/24"
      - "10.20.0.0/24"

  tasks:
    - name: Scan all networks for live hosts (single nmap run)
      ansible.builtin.command: "nmap -sn {{ scan_network_ranges | join(' ') }}"
      register: nmap_output

    - name: Extract IPs from nmap output (unique)
      ansible.builtin.set_fact:
        live_ips: >-
          {{
            (nmap_output.stdout
              | regex_findall('Nmap scan report for (?:[\\w\\-.]+ )?((?:\\d{1,3}\\.){3}\\d{1,3})')
              | unique
            )
          }}

    - name: Print live IPs
      ansible.builtin.debug:
        var: live_ips

    - name: Add IPs to NetBox
      vars:
        ip_payload: |
          {
            "address": "{{ item }}/32"
          }
      ansible.builtin.uri:
        url: "{{ netbox_url }}ipam/ip-addresses/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body: "{{ ip_payload }}"
        body_format: json
        status_code: [201, 400]   # 400 = findes allerede
      loop: "{{ live_ips }}"
      register: netbox_responses

    - name: Show NetBox response summary
      ansible.builtin.debug:
        msg: "Tried {{ item.item }} - HTTP {{ item.status }}"
      loop: "{{ netbox_responses.results }}"
